apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: application-pipeline
spec:
  resources:
    - name: git
      type: git
    - name: output-image
      type: image
  tasks:
  - name: list-source-code
    taskRef:
      name: list-source-code
    resources:
      inputs:
        - name: git
          resource: git
  - name: kaniko-build-and-push-image
    taskRef:
      name: kaniko
    runAfter:
      - list-source-code
    resources:
      inputs:
        - name: source
          resource: git
      outputs:
        - name: image
          resource: output-image
    params:
      - name: CONTEXT
        value: "."
      - name: EXTRA_ARGS
        value: "--skip-tls-verify"
  - name: deploy-application-using-image
    taskRef:
      name: openshift-client
    runAfter:
      - kaniko-build-and-push-image
    params:
      - name: ARGS
        value:
          - "new-app"
          - "--image-stream=nodejsapp"
          - "--name=nodejs-app"
